[package]
name = "client"
publish = false
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
server = { path = "../server" }
game = { path = "../game" }
eframe = "0.15"
clap = "2"
